name: Build & Push Image to ECR

on:
    push:
      branches:
        - main
        - feature*
env:
  ECR_REPOSITORY: swa-ecr 
  EKS_CLUSTER: SHCW-AN2-RND-EKS-1
  CONTAINER_NAME: backstage

permissions:
    id-token: write   
    contents: read    

jobs:
  load_config:
    runs-on: main
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ap-northeast-2

  build:
    name: build image 
    runs-on: feature*, main
    steps:
      - name: install dependency packages 
        run: yarn install
      - name: Build yarn dependencies
        run: yarn build:all
      - name: Copy & build to Docker
        run: yarn build-image --tag ${{ github.sha }}    

  push:
    name: push image to ecr
    runs-on: main
    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: push to ecr repo
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    
  # deploy:
  #   name: deploy image to eks
  #   runs-on: main
  #   steps:
  #     - name: EKS Service
  #       id: eks_service_deployment
  #       uses: aws-actions/amazon-eks-login@v1
  #       run: |
  #         kubectl apply -f kubernetes/backstage.yaml
